### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by LarryEitel** [misterGF/CoPilot#14]
For SOME reason, this project works on one PC but NOT on another. I have same versions of OS, node, npm on both.

Any idea why I get `Uncaught SyntaxError: Unexpected token import` when I launch the page? Thank You :)

```
Uncaught SyntaxError: Unexpected token import
    at Object.<anonymous> (app.js:1710)
    at __webpack_require__ (app.js:556)
    at fn (app.js:87)
    at eval (eval at <anonymous> (app.js:1482), <anonymous>:8:19)
    at Object.<anonymous> (app.js:1482)
    at __webpack_require__ (app.js:556)
    at fn (app.js:87)
    at eval (eval at <anonymous> (app.js:1386), <anonymous>:7:13)
    at Object.<anonymous> (app.js:1386)
    at __webpack_require__ (app.js:556)
```

**Comment by LarryEitel** [comment]
This is the same/related [issue](https://github.com/matfish2/vue-form-2/issues/12) without resolution.

**Comment by LarryEitel** [comment]
Ok, so I installed CoPilot in ANOTHER (parent) directory, outside current dev repo and it runs NO PROB! I then move this working install back into the directory where I have issues with vanilla CoPilot that does NOT work.

`/c/_dk/myProject/CoPilot` <----------- error mentioned above.
`/c/_dk/CoPilot` <------------- WORKS!

remove `/c/_dk/myProject/CoPilot`
move working install `/c/_dk/CoPilot` ----> `/c/_dk/myProject/CoPilot`

now previously working `CoPilot`  `/c/_dk/myProject/CoPilot` fails same as above.

Still digging...

**Comment by LarryEitel** [comment]
`/c/_dk/myProject/CoPilot` works now!
I deleted `/c/_dk/myProject/node_modules`, a sibling directory to CoPilot and it works. How could THAT be culprit!?!

**Comment by bernhardreiter** [comment]
Obviously there must be a difference between the working and the non-working version. The question is how to find the difference that causes the effect.

Just for clarification:
1. You are using "node run dev" , the development server, when getting this problem during compile?
     So it is the same when you do "node run build".
2. This probably is an upstream issue with the combination of vue and webpack. So sooner or later it makes sense to try to open this with https://github.com/vuejs-templates/webpack .

When analysing it, you could try to 'diff' both directories, probably some javascript module is in the search  path for one of the loaders and gets to be used. In the other situation another variante of the same module may be there or is used slightly differently.

**Comment by LarryEitel** [comment]
@bernhardreiter Thank you for sharing your observations. I am running `npm run dev`. Build fails as well. I am suspecting #2 an upstream issue.

**Comment by LarryEitel** [comment]
In the Laravel directory which contains an instance of CoPilot, I deleted the node_modules directory. CoPilot works. I added packages one-by-one to see at what point CoPilot would break.

When I added to devDependancies:

    "laravel-elixir-webpack-official": "^1.0.2"

CoPilot broke. Since in my case I am only using Laravel as a REST service, I don't need that and other related packages. 

It would be nice to understand HOW CoPilot why would not default to local instance rather than from a parent directory.

**Comment by bernhardreiter** [comment]
@LarryEitel good work in finding a trigger to the problem. My suggestion is to try adding this to the official https://github.com/vuejs-templates/webpack (and do whatever you have todo in the parent or system directories) and see if you can reproduce it there. Then filing an upstream issue would certainly drag in more eyes to analyse the problem. 

Note that npm seems to look for system packages in some situations, so it could be an npm problem, too. I'm using yarn now, if you can clone the problem space (parent dir), you could try and see if yarn handles the loading path differently.

**Comment by LarryEitel** [comment]
So sorry. Been on vacation. I have a deadline when I return. Not sure when I will be able to get back to this. If no one else chimes in, I will get to ASAP.
