### ISSUE TITLE
How could I run the generated index.html without moving them into http server www folder?

### ISSUE THREAD

**Issue by xeoshow** [misterGF/CoPilot#16]
Hi,

I am now using websocket javascript api to communiate with my websocket server to get data, so I could open the index.html file directly on PC without any http server. 

I tried CoPilot successfully, while seems I must deploy the generated files in http server www root folder. How could I make it run locally via file opening directly without deploying it to http server?

Thanks a lot!

Best regards, Jason

**Comment by bernhardreiter** [comment]
Hi @xeoshow,
the warning you see when running `npm run build` or ` yarn run build` comes from the https://github.com/vuejs-templates/webpack at https://github.com/vuejs-templates/webpack/blob/8cff712d78e824dbeae0758a0c3f7e9db42d3f63/template/build/build.js
Copilot just uses this webpack setup. My suggestion is that you look and ask at vuejs-templates/webpack instead.

Best,
Bernhard

**Comment by xeoshow** [comment]
Thanks for reply, I undestand those basic concepts, I just want to integrate this CoPilot into my desktop project (Electron), which has no http server as backend, I only add a simple websocket server into my desktop project. And my idea is feed data to CoPilot from websocket server, not http server.

I have managed to replaced the http call with websocket data, while seems the router makes it got problem when opening via file:///, how should I adjust the router to make it work when opening via file:/// ? 

Thanks a lot!

**Comment by bernhardreiter** [comment]
@xeoshow you  won't be the first with this requirements. I guess that if it is vue-router that causes the problem, the vue-router folks will have an answer to this. :)
