### ISSUE TITLE
Dashboard wiggles

### ISSUE THREAD

**Issue by bernhardreiter** [misterGF/CoPilot#18]
If you resize the browser window (size desktop mode) to the point where the vertical scrollbar is going to appear or vanish, the browser enters a resizing loop and visually wiggles.
(tested on a desktop with Chromium	56.0.2924.76 and firefox 45.7.0)

**Comment by bernhardreiter** [comment]
Note that https://github.com/Intevation/intelmq-fody/commit/a052cd19b11fa202472f9985dbf0ec89984f36af should be a workaround. It may actually be an upstream (AdminLTE) issue which is never triggered because their example screens are larger.

**Comment by gustavodemari** [comment]
@bernhardreiter Thanks, it worked.

**Comment by misterGF** [comment]
Fixed in 34e49926
