### ISSUE TITLE
Using SCSS/LESS instead of CSS

### ISSUE THREAD

**Issue by vpiskunov** [misterGF/CoPilot#19]
Is this in the plans? Almaseed do provide the files, but in this repo you only have the blue theme compiled CSS. 

I think it would be great to leverage the power of LESS/SCSS in such a great project as CoPilot. 

Let me know what the plan is, and if not planned, I could look at how to implement this myself.

**Comment by shellscape** [comment]
I'd rather see cssnext + PostCSS over LESS/SCSS. But that is personal opinion :)

**Comment by misterGF** [comment]
@vpiskunov, this would be a great addition. There weren't any plans to get this implemented but I'd accept the PR.

**Comment by vpiskunov** [comment]
See #37 for the PR please. Comments in the PR description.
