### ISSUE TITLE
How can I use datepicker as in the adminlte?

### ISSUE THREAD

**Issue by xeoshow** [misterGF/CoPilot#25]
I do know how to select date via below link, the first input box.
https://copilot.mistergf.io/setting

But how could I set the hours, minutes and seconds after I clicked the datepicker?

In the AdminLTE, it got "Date and time range:" in the below link, seems differrent datepicker component?
https://almsaeedstudio.com/themes/AdminLTE/pages/forms/advanced.html

**Comment by bernhardreiter** [comment]
My suggestion is to switch to a different date-time-picker component. 
I'm just trying https://github.com/jrainlau/vue-flatpickr which can also select the time and date.
