### ISSUE TITLE
cannot compile object.assign error

### ISSUE THREAD

**Issue by danishsoomro** [misterGF/CoPilot#29]
Hey guys, I cloned, npm install and when I npm run dev, I get the following error. Any direction would be appreciate. 
![npm 2017-04-04 18 46 39](https://cloud.githubusercontent.com/assets/2918180/24668498/6433a2d4-1967-11e7-86ee-fa028d4571db.png)

**Comment by danishsoomro** [comment]
THIS IS WHAT I GET WHEN RUN BUILD AFTER FRESH CLONE AND NPM INSTALL

![command prompt 2017-04-04 19 59 35](https://cloud.githubusercontent.com/assets/2918180/24671293/4b03c1a4-1971-11e7-89b8-b46d7c2ae3ff.png)

**Comment by gabn88** [comment]
Seems you have a node version from the renaissance... Try node v6...

**Comment by danishsoomro** [comment]
I created a new ubuntu machine and it worked awesome. Thanks.
