### ISSUE TITLE
"npm install" failed in Windows and Ubuntu

### ISSUE THREAD

**Issue by K69G4JRA725W** [misterGF/CoPilot#30]
Can you make a version that runs in Windows and Ubuntu, please?
Here is the error message.
--------------------------------------------------------------------------------------------------------------
.7924 warn sass-loader@6.0.3 requires a peer of webpack@^2.0.0 but none was installed.
7925 verbose If you need help, you may report this error at:
7925 verbose     <https://github.com/npm/npm/issues>
7926 warn Error: EPERM: operation not permitted, lstat 'D:\castle\CoPilot-master\node_modules\yargs-parser\node_modules'
7926 warn  { Error: EPERM: operation not permitted, lstat 'D:\castle\CoPilot-master\node_modules\yargs-parser\node_modules'
7926 warn   errno: -4048,
7926 warn   code: 'EPERM',
7926 warn   syscall: 'lstat',
7926 warn   path: 'D:\\castle\\CoPilot-master\\node_modules\\yargs-parser\\node_modules' }
7927 verbose Please try running this command again as root/Administrator.
7928 verbose stack Error: node-sass@4.5.2 postinstall: `node scripts/build.js`
7928 verbose stack Exit status 1
7928 verbose stack     at EventEmitter.<anonymous> (D:\applications\node-v7.7.3-win-x64\node_modules\npm\lib\utils\lifecycle.js:279:16)
7928 verbose stack     at emitTwo (events.js:106:13)
7928 verbose stack     at EventEmitter.emit (events.js:194:7)
7928 verbose stack     at ChildProcess.<anonymous> (D:\applications\node-v7.7.3-win-x64\node_modules\npm\lib\utils\spawn.js:40:14)
7928 verbose stack     at emitTwo (events.js:106:13)
7928 verbose stack     at ChildProcess.emit (events.js:194:7)
7928 verbose stack     at maybeClose (internal/child_process.js:899:16)
7928 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
7929 verbose pkgid node-sass@4.5.2
7930 verbose cwd D:\castle\CoPilot-master
7931 error Windows_NT 6.1.7601
7932 error argv "D:\\applications\\node-v7.7.3-win-x64\\node.exe" "D:\\applications\\node-v7.7.3-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "install"
7933 error node v7.7.3
7934 error npm  v4.1.2
7935 error code ELIFECYCLE
7936 error node-sass@4.5.2 postinstall: `node scripts/build.js`
7936 error Exit status 1
7937 error Failed at the node-sass@4.5.2 postinstall script 'node scripts/build.js'.
7937 error Make sure you have the latest version of node.js and npm installed.
7937 error If you do, this is most likely a problem with the node-sass package,
7937 error not with npm itself.
7937 error Tell the author that this fails on your system:
7937 error     node scripts/build.js
7937 error You can get information on how to open an issue for this project with:
7937 error     npm bugs node-sass
7937 error Or if that isn't available, you can get their info via:
7937 error     npm owner ls node-sass
7937 error There is likely additional logging output above.
7938 verbose exit [ 1, true ]

**Comment by euvl** [comment]
```
7926 warn Error: EPERM: operation not permitted, lstat 'D:\castle\CoPilot-master\node_modules\yargs-parser\node_modules'
7926 warn { Error: EPERM: operation not permitted, lstat 'D:\castle\CoPilot-master\node_modules\yargs-parser\node_modules'
```

```
7927 verbose Please try running this command again as root/Administrator.
```

you need to run your npm install as root/admin
