### ISSUE TITLE
when I run the demo, it throw the Exception..

### ISSUE THREAD

**Issue by yb-butterfly** [misterGF/CoPilot#31]
TypeError: (0 , _jquery2.default)(...).DataTable is not a function
    at VueComponent.eval (eval at <anonymous> (app.js:1734), <anonymous>:21:42)
    at Array.eval (eval at <anonymous> (app.js:612), <anonymous>:511:20)
    at nextTickHandler (eval at <anonymous> (app.js:612), <anonymous>:460:16)

**Comment by misterGF** [comment]
Can you give us some more info?

What OS, node version, etc. 

Does it happen when you click on the tables page or after you perform a certain action?

**Comment by yb-butterfly** [comment]
windows7 and my node version is v6.10.2

it happen when i load page without any action

I run the code below:
```
import $ from 'jquery'
// Require needed datatables modules
import 'datatables.net'
import 'datatables.net-bs'

export default {
  name: 'Tables',
  mounted () {
    this.$nextTick(() => {
      console.log($)
      console.log($.DataTable)
      $('#example1').DataTable()
    })
  }
}
```
the result is:
object
undefined

**Comment by misterGF** [comment]
Please reference Euvl's comments on this. https://github.com/misterGF/CoPilot/issues/22

**Comment by hooklife** [comment]
@misterGF 
I have the same problem,how to fix it?
#22 doesn't help me 

`[Vue warn]: Error in nextTick: "TypeError: $(...).DataTable is not a function"`

**Comment by hooklife** [comment]
```
import $ from 'jquery'
// Require needed datatables modules
import 'datatables.net'
import dataTable from 'datatables.net-bs'

export default {
  name: 'User',
  mounted () {
    this.$nextTick(() => {
      $.fn.DataTable = dataTable   // <----- add this line
      $('#example1').DataTable()
    })
  }
}
```
it work!
