### ISSUE TITLE
"npm run dev" failed in Windows 7

### ISSUE THREAD

**Issue by jinchaojian** [misterGF/CoPilot#32]
**when i run “npm install” ，two packages lost .**
"
+-- UNMET PEER DEPENDENCY sinon@1.17.7
+-- UNMET PEER DEPENDENCY webpack@1.14.0
"

"
> copilot@0.5.0 dev D:\phpStudy\WWW\back\CoPilot
> node build/dev-server.js

Listening at http://localhost:8080

webpack built ac839404a9d6118544b5 in 22660ms
Hash: ac839404a9d6118544b5
Version: webpack 1.14.0
Time: 22660ms
     Asset     Size  Chunks             Chunk Names
    app.js  10.2 MB       0  [emitted]  app
index.html  2.15 kB          [emitted]
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  1.47 MB       0
webpack: Compiled successfully.
"
**when I connect to "http://localhost:8080/" ,it's wrong**
"
502 Server dropped connection
The following error occurred while trying to access http://localhost:8080/:
502 Server dropped connection
"

npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.10
3 info using node@v6.9.4
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle copilot@0.5.0~predev: copilot@0.5.0
6 silly lifecycle copilot@0.5.0~predev: no script for predev, continuing
7 info lifecycle copilot@0.5.0~dev: copilot@0.5.0
8 verbose lifecycle copilot@0.5.0~dev: unsafe-perm in lifecycle true
10 verbose lifecycle copilot@0.5.0~dev: CWD: D:\phpStudy\WWW\back\CoPilot
11 silly lifecycle copilot@0.5.0~dev: Args: [ '/d /s /c', 'node build/dev-server.js' ]
12 silly lifecycle copilot@0.5.0~dev: Returned: code: 3221225786  signal: null
13 info lifecycle copilot@0.5.0~dev: Failed to exec dev script
14 verbose stack Error: copilot@0.5.0 dev: `node build/dev-server.js`
14 verbose stack Exit status 3221225786
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid copilot@0.5.0
16 verbose cwd D:\phpStudy\WWW\back\CoPilot
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v6.9.4
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error copilot@0.5.0 dev: `node build/dev-server.js`
22 error Exit status 3221225786
23 error Failed at the copilot@0.5.0 dev script 'node build/dev-server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the copilot package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node build/dev-server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs copilot
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls copilot
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by jinchaojian** [comment]
The problem is node's version.

**Comment by misterGF** [comment]
@jinchaojian  Does that mean you solved your issue? I tried it with node v6.9 and it worked.

**Comment by jinchaojian** [comment]
@misterGF 
Yes,I have solved the problem.I tried it with node v6.10 and it worked.But i tried it with node v6.9 ,it didn't work.

**Comment by misterGF** [comment]
Glad you got it working. Thanks!
