### ISSUE TITLE
Syntax Error: Unexpected token (186:6) Dash.vue

### ISSUE THREAD

**Issue by canhkieu** [misterGF/CoPilot#34]
I try to use CoPilot with Laravel 5.4.
I got this error when run: npm run dev

![image](https://cloud.githubusercontent.com/assets/136077/25119841/fe38ca92-2445-11e7-8f4e-1fa563202a6a.png)

**Comment by misterGF** [comment]
Looks like you removed the spread operator from line 185.

https://github.com/misterGF/CoPilot/blob/42ed5ae8d104e6a62c7cc9cb4fc3b193878b5413/src/components/Dash.vue#L185

Please add it back in and see if that fixes your issue.

For more details on what it does search "Object Spread Operator" on the page below.
https://vuex.vuejs.org/en/state.html#the-mapstate-helper

**Comment by misterGF** [comment]
Been a while since I heard back. Reopen if this doesn't solve your issue
