### ISSUE TITLE
Turn off "dev-mode" for `yarn run build` and `npm run build`

### ISSUE THREAD

**Issue by bernhardreiter** [misterGF/CoPilot#38]
It seems currently vue still believes it is in development mode even if webpack was used to build for production, e.g. by `yarn run build`.

For example if you go to https://copilot.mistergf.io/ and look at the development console
of the browser (e.g. with chromium and vue tools) it still says:
```
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
```

**Comment by bernhardreiter** [comment]
Maybe PR https://github.com/misterGF/CoPilot/pull/26 improves the situation by using improved versions of the vue-cli scaffolding.

**Comment by misterGF** [comment]
This was fixed with that PR!
