### ISSUE TITLE
How to close Bootstrap Modal by vue

### ISSUE THREAD

**Issue by canhkieu** [misterGF/CoPilot#39]
My system login via Modal Bootstrap. How to close this modal after login successful. I try to use
`$('#addFacebookAccountModal').modal('toggle');`

And then it's display this error

`$(...).modal is not a function

**Comment by misterGF** [comment]
Have you tried to use jQuery(...) instead of $(...)? Depending on which version you are working on and your configuration it can vary.

**Comment by MerouaneBoucenna** [comment]
`   $('#myModal').modal('hide');
    $('.modal-backdrop').remove();`
include this two instruction where u want hide the model 
example :
 fetchRoom(){
                fetch() ... 
           .catch(err => console.log(err));
            $('#class').modal('hide');
                $('.modal-backdrop').remove();
                     },

**Comment by ErmenegildoCumbe** [comment]
> ` $('#myModal').modal('hide'); $('.modal-backdrop').remove();`
> include this two instruction where u want hide the modal
> example :
> 
> > fetchRoom(){
> > fetch() ...
> > .catch(err => console.log(err));
> > $('#class').modal('hide');
> > $('.modal-backdrop').remove();
> > },
`$('#myModal').modal('hide');` works perfectly form me.
