### ISSUE TITLE
Current master branch fails to run

### ISSUE THREAD

**Issue by byronferguson** [misterGF/CoPilot#41]
Everything but the "build" run option fails.  running the most current node.js and npm

17 error Windows_NT 6.3.9600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v6.10.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error copilot@0.5.0 dev: `node build/dev-server.js`
22 error Exit status 1
23 error Failed at the copilot@0.5.0 dev script 'node build/dev-server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the copilot package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node build/dev-server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs copilot
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls copilot
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by misterGF** [comment]
I wasn't able to replicate this issue. Any errors when you did npm install from the root of the project? Running the shell as administrator?

**Comment by byronferguson** [comment]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm WARN karma-sinon-chai@1.3.1 requires a peer of sinon@^2.1.0 but none was installed.

**Comment by misterGF** [comment]
Pull the latest commit. It was fixed earlier.

On Fri, May 12, 2017 at 9:02 PM, Byron Ferguson <notifications@github.com> wrote:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm WARN karma-sinon-chai@1.3.1 requires a peer of sinon@^2.1.0 but none was installed.

**Comment by byronferguson** [comment]
C:\Users\byron.ferguson\git\CoPilot>git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.

This is as of now, and the build fail is still the same

**Comment by misterGF** [comment]
Do a git pull to get the latest.

**Comment by byronferguson** [comment]
I appreciate your responsiveness; however, I am already current, and a git pull confirmed that.  You should see that I am using npm 4.5.0 and node 6.10.2 both of which are the latest releases.

**Comment by misterGF** [comment]
The last error/warning you posted was 
npm WARN karma-sinon-chai@1.3.1 requires a peer of sinon@^2.1.0 but none was installed.

The current package.json file is locked to version 1.2.4
https://github.com/misterGF/CoPilot/blob/master/package.json#L75 

Previously it was. "karma-sinon-chai": "^1.2.4", 

Note the ^. Inspect your package.json and make sure that is not there and try to npm install again.

That should work but in case it doesn't you might want to try to re-clone the repo from a new folder or remove the node_modules folder and install them again once the package.json is corrected.

**Comment by byronferguson** [comment]
package.json is correct

"karma-sinon-chai": "1.2.4",

the "karma-sinon-chai" value is locked to 1.2.4

**Comment by byronferguson** [comment]
`PS C:\Users\byron.ferguson\git\CoPilot> npm run dev

> copilot@0.5.0 dev C:\Users\byron.ferguson\git\CoPilot
> node build/dev-server.js

> Starting dev server...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at EventEmitter.listen (C:\Users\byron.ferguson\git\CoPilot\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (C:\Users\byron.ferguson\git\CoPilot\build\dev-server.js:84:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! copilot@0.5.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the copilot@0.5.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the copilot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs copilot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls copilot
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\byron.ferguson\AppData\Roaming\npm-cache\_logs\2017-05-15T16_14_01_037Z-debug.log`

**Comment by misterGF** [comment]
The error is pretty clear here: Error: listen EADDRINUSE :::8080

**Comment by byronferguson** [comment]
Hallelujah! It finally builds and runs. Now to see if I can figure out the framework for my project.
Thank you.
