### ISSUE TITLE
logo scaling does not fit

### ISSUE THREAD

**Issue by bernhardreiter** [misterGF/CoPilot#43]
Today on https://copilot.mistergf.io/ the logo on the top left scales in xs mode. I'd expect it not to scale (and I think it did not in earlier versions). See how the logo and the text start to vanish:

![copilot-20170511-1](https://cloud.githubusercontent.com/assets/8190008/25957833/7dc6b1b2-366f-11e7-9663-db8b51c64cae.png)
![copilot-20170511-2](https://cloud.githubusercontent.com/assets/8190008/25957832/7dbe5ad0-366f-11e7-872b-ee52d30fe505.png)

**Comment by misterGF** [comment]
Fixed in latest 70ef8c9
