### ISSUE TITLE
Strange moving on screen

### ISSUE THREAD

**Issue by gustavodemari** [misterGF/CoPilot#44]
See the gif below

![](http://i.imgur.com/LIk9jI2.gif)
http://i.imgur.com/LIk9jI2.gifv

Google Chrome
Version 58.0.3029.81 (64-bit)

When I open the Chrome Developer Tools, the problem stops.

Also, this problem doesn't happen in Firefox 53.0.2.

**Comment by bernhardreiter** [comment]
That is a duplicate of #18

**Comment by gustavodemari** [comment]
Closed as pointed by @bernhardreiter
