### ISSUE TITLE
Requiring authentication failing

### ISSUE THREAD

**Issue by martingsaunders** [misterGF/CoPilot#52]
I'm trying to get the theme to require authentication for pages except 'login'. The code is there to detect whether a route requires authentication but I can't get it to function.

In:

`// Some middleware to help us ensure the user is authenticated.
router.beforeEach((to, from, next) => {
  // window.console.log('Transition', to)
  if (to.auth && (to.router.app.$store.state.token === 'null')) {
    window.console.log('Not authenticated')
    next({
      path: '/login',
      query: { redirect: to.fullPath }
    })
  } else {
    next()
  }
})`

I can't get `to.auth` to exist and likewise `to.router` always seems to be undefined. 

How do I get these parameters to exist?

Brilliant project btw!

**Comment by misterGF** [comment]
Thank you!

You should be able to add the auth property to the routes that need it.
https://github.com/misterGF/CoPilot/blob/master/src/routes.js 


``` javascript
{
        path: 'setting',
        component: SettingView,
        auth: true,
        name: 'Settings',
        meta: {description: 'User settings page'}
}

```

**Comment by martingsaunders** [comment]
I tried that but the auth property didn't come through in the beforeeach method. There there was also still no route object attached to the 'to' object. I followed the changes in pull request #27 though and that worked fine.

Thanks.
