### ISSUE TITLE
dropdown user user-menu

### ISSUE THREAD

**Issue by adanwo** [misterGF/CoPilot#60]
The component Dash.vue contains a "dropdown user user-menu" element, but when I click the button the drop-down menu does not work. However in Admin-LTE it works correctly, only en Copilot version fails.

**Comment by misterGF** [comment]
@adanwo Copilot isn't a direct copy of AdminLTE. Some components were taken out, this being one of them. The good news is that you can add it back in pretty easily! 
Just add in the html to your version of CoPilot.

https://github.com/almasaeed2010/AdminLTE/blob/f4ee8fba6839c02d0a919f08c3396bc1fb0abf59/pages/layout/top-nav.html#L169
