### ISSUE TITLE
Firebase integration and authentication?

### ISSUE THREAD

**Issue by nkrvivek** [misterGF/CoPilot#63]
Any plans on adding firebase integration and authentication so it can be run in a serverless environment?

**Comment by misterGF** [comment]
No plans to add integration but it should be fairly easy to do if you choice to go with firebase. I use Sails and more recently aws lambda. A wiki on how to integrate it would be helpful. Let me know if you want to provide that or if you need some assistance with understanding the implementation needs.

**Comment by nkrvivek** [comment]
It would be helpful to have some sample implementation to use firebase as the backend and for authentication.

**Comment by misterGF** [comment]
https://vuejs.org/v2/examples/firebase.html
