### ISSUE TITLE
Can't build proper dist - path into subfolder broken

### ISSUE THREAD

**Issue by Bear4** [misterGF/CoPilot#66]
Trying move CoPilot vueapp into outer server.
When 
npm run build 
I got 
dist/index.html and others dist/stat/*.*  with path http://myserver/
but I have subfolder on myserver.
Revrited path in config/index.js:
```
  build: {
    env: require('./prod.env'),
    index: path.resolve(__dirname, '../dist/index.html'),
    assetsRoot: path.resolve(__dirname, '../dist'),
    assetsSubDirectory: 'static',
    **assetsPublicPath: '/CoPilot'**,
    productionSourceMap: true,
    productionGzip: false,
    productionGzipExtensions: ['js', 'css']
  },
```

after npm run build and move file into myserver/CoPilot
there is no proper path into index.html, after revrite path in index.html that doesn't work proper too.
My index.html path after build:

```
<link rel="shortcut icon" type=image/x-icon href=static/img/favicon.ico>
<link rel=stylesheet href=/static/css/bootstrap.min.css>
<link rel=stylesheet href=/static/css/AdminLTE.min.css>
<link rel=stylesheet href=/static/css/skin-blue.min.css>
<link rel=stylesheet href=/static/js/plugins/pace/pace.min.css><!--[if lt IE 9]>
    <![endif]--><link href=/CoPilot/static/css/app.8c162f4971b15fdc9c89bd87efa3d22f.css rel=stylesheet></head>
	<script src=/static/js/plugins/jQuery/jQuery-2.2.0.min.js>
	</script><script src=/static/js/plugins/bootstrap/bootstrap.min.js>
	</script><script src=/static/js/plugins/AdminLTE/app.min.js></script>
	<script src=/static/js/plugins/pace/pace.min.js></script>
     // analytics section
      ga('create', 'YOUR_SHIT_HERE', 'auto')
      ga('send', 'pageview')</script>
	  <script type=text/javascript src=/CoPilot/static/js/manifest.9432c8d67b4c559c6f6e.js></script>
	  <script type=text/javascript src=/CoPilot/static/js/vendor.d92efcb3c47e3850684d.js></script>
	  <script type=text/javascript src=/CoPilot/static/js/app.60d8909872812e4b3685.js></script></body></html>
```
As You see above in some place I have changed path in the others I haven't...
Could You give me direction where I should rewrite my path to get proper dist files (to server/subfolder )?

Thanks in advance

**Comment by Bear4** [comment]
There are two files:
1. config/index.js in module build (line 5 to 18) change line 10:
from: `assetsPublicPath: '/', `to: `assetsPublicPath: '/my_subfolder/',`
2. main.js if use router:
```
// Routing logic
var router = new VueRouter({
  routes: routes,
  mode: 'history',
  base: '/my_subfolder', // add base to proper path generate for build dist
  linkExactActiveClass: 'active',
  scrollBehavior: function (to, from, savedPosition) {
    return savedPosition || { x: 0, y: 0 }
  }
})
```
There is third places but I don't found till now :)
Just replace before `npm run build` in dist/index.html to proper and works fine for me.

Additional there may be in code (src/components/views/Tables.vue) set references to another library / styles e.g.:
so changed from: 
`@import url('/static/js/plugins/datatables/dataTables.bootstrap.css');` 
to: 
`@import url('/my_subfolder/static/js/plugins/datatables/dataTables.bootstrap.css');`

I have billboard.js library there (src/components/views/Dashboard.vue)
so changed from: 
`@import url('/static/js/plugins/billboardjs/billboard.min.css');` 
to: 
`@import url('/my_subfolder/static/js/plugins/billboardjs/billboard.min.css');`

And last file for me (src/components/views/Dash.vue) where is path into logo CoPilot in template line 5 :
so changed from:
`<img src="/static/img/copilot-logo-white.svg" alt="Logo" class="img-responsive center-block logo">`
to:
`<img src="/my_subfolder/static/img/copilot-logo-white.svg" alt="Logo" class="img-responsive center-block logo">`
 Of course must change back inline code when `npm run dev` because in dev mode my references would be broken :/

I would be gratefull for point me this third place where I can set path for build mode.

**Comment by hellower** [comment]
dev-server.js

1. add below line
var history = require('connect-history-api-fallback');

2. change
app.use(require('connect-history-api-fallback')())
==>
app.use(history({
  rewrites: [
    { from: /^\/my_subfolder(\/?)$/, to: '/my_subfolder/index.html'}
  ]
}))
