### ISSUE TITLE
Test run FAILED

### ISSUE THREAD

**Issue by rflaperuta** [misterGF/CoPilot#67]
Tryed it today and Im getting:

npm run test

> copilot@0.5.0 test /home/xxxxxxxxxxxxx/Projetos/CoPilot
> npm run unit && npm run e2e

> copilot@0.5.0 unit /home/rodrigo.laperuta/Projetos/CoPilot
> cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run

31 01 2018 19:06:49.586:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
31 01 2018 19:06:49.588:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
31 01 2018 19:06:49.619:INFO [launcher]: Starting browser PhantomJS
31 01 2018 19:06:52.518:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket 0MOT_IBd3Qf0ZN75AAAA with id 77696946
31 01 2018 19:06:52.845:WARN [web-server]: 404: /static/js/plugins/datatables/dataTables.bootstrap.css
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  TypeError: undefined is not an object (evaluating 'DataTable.defaults')
  at webpack:///~/datatables.net-bs/js/dataTables.bootstrap.js:47:0 <- index.js:71285

PhantomJS 2.1.1 (Linux 0.0.0): Executed 0 of 0 ERROR (0.723 secs / 0 secs)

PhantomJS 2.1.1 (Linux 0.0.0) INFO LOG: 'You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html'

**Comment by misterGF** [comment]
Thanks for the report.

Can you pull the latest and try again? It should be fixed.

**Comment by misterGF** [comment]
will take no news as good news! Please open up a new issue if you still have issues.
