### ISSUE TITLE
When the sidebar is collapsed, hovering over a Treeview element does not show the element's name

### ISSUE THREAD

**Issue by liamrathke** [misterGF/CoPilot#69]
Basically, when the sidebar is collapsed and I hover over the icon for one of the list elements, and this list element is a Treeview, the list element's title does not show.

Sidebar collapsed, icon hovered over (issue):
<img width="261" alt="screen shot 2018-04-11 at 12 07 14 pm" src="https://user-images.githubusercontent.com/33555592/38629367-da264502-3d81-11e8-89bb-933ed06bf8a2.png">

Sidebar expanded, showing the same Treeview: 
<img width="262" alt="screen shot 2018-04-11 at 12 07 23 pm" src="https://user-images.githubusercontent.com/33555592/38629434-ffb104c4-3d81-11e8-8e2d-9f4d57e7499d.png">

This feature works on the official [AdminLTE example](https://adminlte.io/themes/AdminLTE/index2.html), so I'm assuming that the `<router-link>` element might be interfering. Here's what it looks like there:
<img width="257" alt="screen shot 2018-04-11 at 12 07 39 pm" src="https://user-images.githubusercontent.com/33555592/38629516-4365c042-3d82-11e8-886c-183a197a31c5.png">

**Comment by liamrathke** [comment]
I found a fix to this on my own, the solution is to set the text (in this case, "files"), to have a z-index of 1. 

The text was not displayed since the arrow icon was somehow interfering.

**Comment by misterGF** [comment]
Great! Can you send a pull request to fix it in the project as well?

**Comment by liamrathke** [comment]
Sure, I'll get to it later today!
