### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by yogaaaaa** [misterGF/CoPilot#73]
Error: EACCES: permission denied, open 'geckodriver.tar.gz'
Emitted 'error' event at:
    at WriteStream.onerror (/Users/yoga/frontend/CoPilot-master/node_modules/readable-stream/lib/_stream_readable.js:633:52)
    at WriteStream.emit (events.js:182:13)
    at fs.open (fs.js:2233:12)
    at FSReqWrap.oncomplete (fs.js:152:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! geckodriver@1.10.0 postinstall: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the geckodriver@1.10.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2018-05-28T18_22_23_668Z-debug.log

**Comment by misterGF** [comment]
You try running your command with sudo?
Can you let me know the command and OS you are using?

**Comment by bluestrat404** [comment]
Same issue here, even when running with sudo: "sudo npm install". OS is macOS 10.13.4

**Comment by zpetrovic** [comment]
I had the same issue when running "$ sudo npm install" after cloning repo.
Everything is OK if I run "$ npm install". This will not fix it if you already run it with "$ sudo", just clone repo again.

**Comment by IvanNetto** [comment]
Hey ... same problem here ... did anybody fix it?

**Comment by misterGF** [comment]
Are you having issues with the geckodriver as well or just issues with the npm install process? Posting specifics would help. Please also update your copy with the latest commit. Fixed an issue with node-saas.

**Comment by dhalsted** [comment]
Ran into this issue with geckodriver on OSX and was able to get the install working by re-cloning and doing 'npm install' instead of 'sudo npm install'.  Looks like a lot of vulnerabilities in there, though, including 4 criticals.

**Comment by rommyarb** [comment]
> Ran into this issue with geckodriver on OSX and was able to get the install working by re-cloning and doing 'npm install' instead of 'sudo npm install'. Looks like a lot of vulnerabilities in there, though, including 4 criticals.

You are right! I did `npm install` instead of `sudo npm install` and it works!

**Comment by CharmiBhikadiya** [comment]
> Ran into this issue with geckodriver on OSX and was able to get the install working by re-cloning and doing 'npm install' instead of 'sudo npm install'. Looks like a lot of vulnerabilities in there, though, including 4 criticals.

Your solution works, thanks a lot!. But I am very curious to know the reason not working using sudo npm install. Any thoughts?
