### ISSUE TITLE
Cannot run project

### ISSUE THREAD

**Issue by InsiderTI** [misterGF/CoPilot#74]
I run the commands:
git clone https://github.com/misterGF/CoPilot.git
cd CoPilot
npm install

Then a message appears:

added 1271 packages from 1602 contributors and audited 8206 packages in 89.456s
found 318 vulnerabilities (269 low, 29 moderate, 16 high, 4 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

A just ignore the message and try to run:

npm run dev

Then a message appears:

Module build failed: Error: Failed to find '/static/js/plugins/datatables/dataTables.bootstrap.css'

But the file exists. So I try change permissions for a more permissive:
cd ..
chmod 777 -R CoPilot

But not working... So I try:

npm audit fix

But still not working... Any ideas ?

**Comment by InsiderTI** [comment]
Got it. In "Tables.vue" change
@import url('/static/js/plugins/datatables/dataTables.bootstrap.css');
to
@import url('../../../static/js/plugins/datatables/dataTables.bootstrap.css');

But now I facing the error when I open the page:
TypeError: DataTable is undefined

**Comment by InsiderTI** [comment]
Got it:
npm install datatables.net --save

**Comment by InsiderTI** [comment]
Next error: Property or method "styleObj" is not defined on the instance but referenced during render.

**Comment by KayserDevelopers8770** [comment]
Hi, I need to buy the original version of this admin Copilot template, How I can do?

**Comment by misterGF** [comment]
@InsiderTI. The datatable issue has been resolved in the latest commit. We need to require instead of importing it in the tables.vue page. Try to sync the changes to see if it will help you.

Thanks.

**Comment by InsiderTI** [comment]
Ok @misterGF. Now is working if I not update the packages. However, many packages have vulnerabilities. If I try to update them with **npm audit fix**:
Then:

**added 1210 packages from 1585 contributors and audited 7839 packages in 98.631s
found 303 vulnerabilities (266 low, 18 moderate, 15 high, 4 critical)**

then I run: **npm audit fix** 
And:

+ http-server@0.11.1
+ karma-coverage@1.1.2
+ babel-core@6.26.3
+ copy-webpack-plugin@4.5.2
+ http-proxy-middleware@0.19.0
+ geckodriver@1.12.2
+ babel-preset-env@1.7.0
added 147 packages from 85 contributors, removed 18 packages and updated 69 packages in 78.024s
fixed 266 of 303 vulnerabilities in 7839 scanned packages
  11 package updates for 37 vulns involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)

So a try to run "**npm run dev**" to see if still working, but a error message appears:

ERROR  Failed to compile with 1 errors                                                                                                      19:35:45

This dependency was not found:

* jquery in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/views/Tables.vue

**Comment by misterGF** [comment]
Right. This is a tough one because there are sub-dependencies that cause those alerts. As far as jQuery. You might be able to get away with including it as a script tag in your HTML instead of loading it as a node module. Alternately, you can look at the new version and see how it can fit into the stack. PRs are welcome.

**Comment by InsiderTI** [comment]
Ok. Thanks @misterGF !
